version: 2
jobs:
  build:
    docker:
      - image: rocker/ropensci
    steps:
      - checkout
      - run: 
        name: build
        command: Rscript build.R
        no_output_timeout: 60m
      - run: bash git_deploy.sh

